"""Shared contracts and support code."""

from openclaw_moneybot.shared.bitcoin import (
    AddressValidationResult,
    normalize_btc_address_for_comparison,
    validate_btc_address,
)
from openclaw_moneybot.shared.config import (
    AppConfig,
    ArchiveConfig,
    ArtifactRendererConfig,
    BrowserGovernorConfig,
    CounterpartySnapshotConfig,
    DeadlineSchedulerConfig,
    DownloadQuarantineConfig,
    EmailConfig,
    InboxObserverConfig,
    LedgerConfig,
    MetricsExportConfig,
    MoneyBotPolicyConfig,
    OperatorProfileStoreConfig,
    OpportunityIndexConfig,
    RulesSnapshotGatewayConfig,
    WalletGovernorConfig,
    WalletObserverConfig,
    load_app_config,
)
from openclaw_moneybot.shared.contracts import (
    BudgetPlan,
    EmailDraftRecord,
    EvidenceRecord,
    ExperimentReview,
    LedgerRecord,
    MoneyBotAction,
    Opportunity,
    PolicyDecision,
    SpendRequest,
    TosLegalCheck,
    WalletTransactionRecord,
)
from openclaw_moneybot.shared.errors import ErrorCode, MoneyBotError, MoneyBotErrorDetail
from openclaw_moneybot.shared.types import (
    BitcoinNetwork,
    SpendRequestStatus,
    WalletTransactionStatus,
)

__all__ = [
    "AppConfig",
    "ArchiveConfig",
    "AddressValidationResult",
    "ArtifactRendererConfig",
    "BitcoinNetwork",
    "BrowserGovernorConfig",
    "BudgetPlan",
    "CounterpartySnapshotConfig",
    "DeadlineSchedulerConfig",
    "DownloadQuarantineConfig",
    "EmailConfig",
    "EmailDraftRecord",
    "ErrorCode",
    "EvidenceRecord",
    "ExperimentReview",
    "InboxObserverConfig",
    "LedgerConfig",
    "LedgerRecord",
    "MetricsExportConfig",
    "MoneyBotAction",
    "MoneyBotError",
    "MoneyBotErrorDetail",
    "MoneyBotPolicyConfig",
    "normalize_btc_address_for_comparison",
    "OperatorProfileStoreConfig",
    "Opportunity",
    "OpportunityIndexConfig",
    "PolicyDecision",
    "RulesSnapshotGatewayConfig",
    "SpendRequest",
    "SpendRequestStatus",
    "TosLegalCheck",
    "WalletObserverConfig",
    "WalletGovernorConfig",
    "WalletTransactionRecord",
    "WalletTransactionStatus",
    "validate_btc_address",
    "load_app_config",
]
